### DISCUSSION TITLE
Create a New Journal and Folder for it?

### DISCUSSION THREAD

**Discussion by wfloydiv** [jrnl-org/jrnl#1635] [Q&A] [answered]
How do I make a new journal in the config and then set a path for it to put the files into that isn't by default, like where do I place this in the config and how do I even create a new journal?

**Comment by wren** [comment, marked as answer]
Hi, @wfloydiv. Thanks for your question.

The information you're looking for is currently in the [Advanced Usage](https://jrnl.sh/en/stable/advanced/) section of our docs. 

Basically, you need to add a new section under `journals` in your config file. Here's what it might look like if you had three journals named `default`, `work`, and `food`:

```yaml
encrypt: false
journals:
  default: ~/journal.txt
  work:
    journal: ~/work.txt
    encrypt: true
  food: ~/my_recipes.txt
```

That being said, though, maybe our docs would benefit from having a dedicated "How to create a new journal" section. Thanks for bringing this up!
