### DISCUSSION TITLE
How to change date format?

### DISCUSSION THREAD

**Discussion by rghedin** [jrnl-org/jrnl#1840] [Q&A] [answered]
Just started using jrnl, it's awesome!

I notice that jrnl defaults to US date format, as in MM/DD/YYYY and using AM/PM time. I live in Brazil, where things are slightly different (as is in most countries): DD/MM/YYYY and 24h time.

Is it possible to change this configuration? If so, how?

**Comment by micahellison** [comment, marked as answer]
Hi @rghedin, I'm glad you're liking jrnl. It is possible to set up a journal using a non-US date/time format, though I only recommend doing this with a new journal since jrnl will have a hard time understanding what the old dates mean if you change an existing journal's configuration.

To change it in the [config](https://jrnl.sh/en/stable/reference-config-file/), use the timeformat key in your journal, like so:
```
journals:
  brazil-time:
    journal: C:\temp\testing\brazil-time.jrnl
    timeformat: '%d/%m/%Y %H:%M:%S'
```
