### ISSUE TITLE
Configure default display format in config

### ISSUE THREAD

**Issue by wren** [jrnl-org/jrnl#1014]
## Feature Request

This request comes out of #996. 

### Use Case/Motivation

Some users always want to display their journals in a specific format. They can do that now by adding `--format markdown` (since v2.5) or `--export markdown` to each command. This is tedious and long. Sure, users can make an alias, but the `--format` flag can get in the way of certain commands (like `--edit`).

So, the idea came up to be able to specify a default format (either global, or per journal).

### Example Usage

If the config file has, say:
```yaml
journals:
  default:
    encrypt: true
    display_format: markdown
    journal: ~/Documents/Journals/default.txt

```
`jrnl -1` would output the same way as `jrnl -1 --format markdown` would.

Also, `jrnl -1 --format text` should still work (override the config file).

### Other information

If a format doesn't exist, jrnl should output an error message, and fallback to our default jrnl format.
