### ISSUE TITLE
decrypt jrnl file in dropbox on another machine fails 

### ISSUE THREAD

**Issue by albertwh1te** [jrnl-org/jrnl#1019]
### Environment
  - Jrnl version: jrnl version v2.4.4
  - Install method: pip
  - OS: Ubuntu and MacOS

### Current Behavior
I encrypt jrnl file with 
`jrnl --encrypt
`
 on Ubuntu and keep my encrypted file in dropbox 
When I want to add one entry on Mac, jrnl asks me to enter the password.  I entered the password. Jrnl keeps telling me this password is wrong. But if I use the same password on Ubuntu, it works.  

### Expected Behavior
I wish I can use the same password on the different machines. 
### Repro Steps
encrypt jrnl  on a Ubuntu 
and copy the file to a Mac and try to add one entry.
### Other Information
my config is 
```

colors:       
  body: none    
  date: none    
  tags: none    
  title: none    
default_hour: 9    
default_minute: 0    
editor: vim    
encrypt: false    
highlight: true    
indent_character: '|'    
journals:    
  default:    
    encrypt: true    
    journal: /home/mark/Dropbox/diary/jrnl_linux.txt    
linewrap: 79    
tagsymbols: '@'    
template: false    
timeformat: '%Y-%m-%d %H:%M'    
version: v2.4.4    
```
