### ISSUE TITLE
Different templates for different journals

### ISSUE THREAD

**Issue by todonnell** [jrnl-org/jrnl#1152]
## Feature Request
Associate different template files with different journals.

### Use Case/Motivation
It would be useful to have different prompts for different journals.

### Example Usage
in the config file: 
journals:
  stuff:
   file: ~/.journals/stuff.txt
   template: ~/.journals/stuff_template.txt

**Comment by micahellison** [comment]
Hi there, this feature does exist in jrnl. Your example configuration is just a little bit off, and should be using the `journal` key instead of the `file` key, like so:

```
journals:
  stuff:
    journal: ~/.journals/stuff.txt
    template: ~/.journals/stuff_template.txt
```
There's more info on how this works in the [Advanced section](https://jrnl.sh/en/stable/advanced/#multiple-journal-files) of the docs.
