### ISSUE TITLE
Integration with vim-ultisnips

### ISSUE THREAD

**Issue by rsvdr** [jrnl-org/jrnl#1448]
## Feature Request

Use a [vim-ultisnip](https://github.com/SirVer/ultisnips) snippet instead of plain text as a template.

### Use Case/Motivation

This facilitates jrnl template edit by using ultisnips *replacement* and *jump* capabilities.

### Example Usage

Consider a foo jrnl configured as:

```
# jrnl.yaml
  foo:
    journal: /home/user/path/to/notes/foo.jrnl
    template: /home/user/.config/jrnl/snippets/template-foo.jrnl
```

On `jrnl foo` a bar snippet is called. 

The bar snippet is defined in a `template-foo.jrnl` file

```
# template-foo.jrnl
snippet bar "bar snippet"
${1:TITLE}
key1: ${2:VAL1}
key2: ${3:VAL2}
endsnippet 
```

which follows ultisnip snippet syntax.
